= TDL Go
:toc:
:toc-placement!:
:icons: font

:golang-uri: https://golang.org
:golang-doc-uri: {golang-uri}/doc
:github-uri: https://github.com

.Sommaire
toc::[]


== Introduction

Go est un language qui buzz beaucoup depuis quelques temps, j'ai donc eut l'envie de m'initier à ce langage.

Je suis demandé comment commencer : faire des tutoriels, souvent cela se résume à des copier-coller et finit par une connaissance très partielle.

Du coup, je suis dit pourquoi ne pas essayer de faire le kata FizzBuzz pour apprendre.

C'est un kata très simple que je connais bien, je l'ai fait avec différentes contraintes en Java alors pourquoi ne pas le faire en Go ?

C'est parti !


== Point de départ

Le site officiel de Go : {golang-uri}.

Pour commencer, j'ai installé Go.
C'est plutôt simple, tout se trouve à cette adresse suivante : {golang-uri}/dl.

Après il me fallait un minimum de documentation sur le langage.
N'étant pas un grand fan de StackOverflow, j'aime les sites contenant la documentation et les samples officiels.

J'ai trouvé 4 points d'entrées qui m'ont semblé pertinent :

- {golang-doc-uri}
- {golang-doc-uri}/effective_go.html
- {golang-uri}/ref/spec
- {github-uri}/golang/go/wiki


== La structure


== Les tests


== IDE


== Le langage


== Le kata


== Et après ?
